GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTY1NTc1NTQzNiwiZXhwIjoxNjU1NzU1NDUxfQ.wNe-sxDxjadHf0dJDSDILfm0P_mW_oJUhK1MEmn_NQs

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTY1NTc1NTQwN30.QWWXwH0yMe-2iaT0DbEf5vLpFC0P4nPAOpK9y-yYLvE"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTY1NTc1NTQwN30.QWWXwH0yMe-2iaT0DbEf5vLpFC0P4nPAOpK9y-yYLvE"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "kyle"
}